import type { ActivitySession, AvailabilitySlot, ComfortKey, Interest, ResidentProfile } from "./types";

export const brandAssets = {
  logoWordmark: "Gezellig",
  logoMark: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Ccircle cx='32' cy='32' r='30' fill='%23ff8c32'/%3E%3Ccircle cx='24' cy='28' r='3.5' fill='white'/%3E%3Ccircle cx='40' cy='28' r='3.5' fill='white'/%3E%3Cpath d='M20 38c3 6 7 9 12 9s9-3 12-9' stroke='white' stroke-width='3.5' stroke-linecap='round' fill='none'/%3E%3C/svg%3E",
  heroImage: "https://www.figma.com/api/mcp/asset/6a35cccc-51a2-4ddb-b303-8a754ceaf661",
  cityCardImage: "https://www.figma.com/api/mcp/asset/62bb4bb6-a083-43a3-8305-ae2948979bee",
  profileCardImage: "https://www.figma.com/api/mcp/asset/aaeeafc5-e073-4507-927a-7aaa80cebaa5",
};

export const activityImages: Record<Interest, string> = {
  walking: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=300&h=300&fit=crop&q=80",
  museums: "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?w=300&h=300&fit=crop&q=80",
  coffee: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=300&h=300&fit=crop&q=80",
  studying: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=300&h=300&fit=crop&q=80",
  padel: "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=300&h=300&fit=crop&q=80",
  football: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=300&h=300&fit=crop&q=80",
  basketball: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=300&h=300&fit=crop&q=80",
  fencing: "https://images.unsplash.com/photo-1599586120429-48281b6f0ece?w=300&h=300&fit=crop&q=80",
  hackathons: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=300&h=300&fit=crop&q=80",
  board_games: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=300&h=300&fit=crop&q=80",
  cooking: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=300&h=300&fit=crop&q=80",
  cinema: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=300&h=300&fit=crop&q=80",
  community_events: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=300&h=300&fit=crop&q=80",
  yoga: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=300&h=300&fit=crop&q=80",
  cycling: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=300&h=300&fit=crop&q=80",
  photography: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=300&h=300&fit=crop&q=80",
  music: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=300&h=300&fit=crop&q=80",
  gardening: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop&q=80",
  crafts: "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=300&h=300&fit=crop&q=80",
  swimming: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=300&h=300&fit=crop&q=80",
  dancing: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&h=300&fit=crop&q=80",
  languages: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=300&h=300&fit=crop&q=80",
  other: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=300&h=300&fit=crop&q=80",
};

export const peopleCards = [
  {
    name: "Ann James",
    image: "https://www.figma.com/api/mcp/asset/6a35cccc-51a2-4ddb-b303-8a754ceaf661",
    note: "Walking nearby",
    daysLeft: "7 days left",
  },
  {
    name: "Lauren Brand",
    image: "https://www.figma.com/api/mcp/asset/62bb4bb6-a083-43a3-8305-ae2948979bee",
    note: "Museum coffee",
    daysLeft: "7 days left",
  },
  {
    name: "Alex Thomas",
    image: "https://www.figma.com/api/mcp/asset/aaeeafc5-e073-4507-927a-7aaa80cebaa5",
    note: "Board games",
    daysLeft: "4 days left",
  },
  {
    name: "Nora van Dijk",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80",
    note: "Hackathons",
    daysLeft: "5 days left",
  },
  {
    name: "Youssef El Amrani",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&q=80",
    note: "Basketball nearby",
    daysLeft: "6 days left",
  },
  {
    name: "Mila de Boer",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
    note: "Fencing beginner",
    daysLeft: "8 days left",
  },
  {
    name: "Jasper Visser",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    note: "Board games",
    daysLeft: "3 days left",
  },
  {
    name: "Priya Sharma",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    note: "Coffee and coding",
    daysLeft: "7 days left",
  },
  {
    name: "Samira Bakker",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=80",
    note: "Language table",
    daysLeft: "9 days left",
  },
  {
    name: "Thomas Meijer",
    image: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=200&q=80",
    note: "Football Sundays",
    daysLeft: "2 days left",
  },
  {
    name: "Elena Petrova",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&q=80",
    note: "Photography walks",
    daysLeft: "10 days left",
  },
];

export const interests: { id: Interest; label: string }[] = [
  { id: "coffee", label: "Coffee" },
  { id: "cinema", label: "Cinema" },
  { id: "football", label: "Football" },
  { id: "basketball", label: "Basketball" },
  { id: "fencing", label: "Fencing" },
  { id: "hackathons", label: "Hackathons" },
  { id: "padel", label: "Padel" },
  { id: "walking", label: "Walking" },
  { id: "museums", label: "Museums" },
  { id: "board_games", label: "Board games" },
  { id: "studying", label: "Study session" },
  { id: "cooking", label: "Cooking" },
  { id: "community_events", label: "Local events" },
  { id: "yoga", label: "Yoga" },
  { id: "cycling", label: "Cycling" },
  { id: "photography", label: "Photography" },
  { id: "music", label: "Music" },
  { id: "gardening", label: "Gardening" },
  { id: "crafts", label: "Crafts" },
  { id: "swimming", label: "Swimming" },
  { id: "dancing", label: "Dancing" },
  { id: "languages", label: "Languages" },
  { id: "other", label: "Other" },
];

export const comfortOptions: { id: ComfortKey; label: string; helper: string }[] = [
  { id: "smallGroups", label: "Small groups", helper: "2-5 people" },
  { id: "oneToOne", label: "1:1 optional", helper: "Only if you choose it" },
  { id: "publicPlacesOnly", label: "Public places", helper: "Visible venues first" },
  { id: "communityHosted", label: "Hosted events", helper: "Partner or venue present" },
];

export const availabilityOptions: AvailabilitySlot[] = [
  { day: "Wednesday", label: "Wed afternoon", startTime: "15:00", endTime: "17:00" },
  { day: "Thursday", label: "Thu evening", startTime: "18:30", endTime: "20:00" },
  { day: "Saturday", label: "Sat morning", startTime: "10:00", endTime: "12:00" },
  { day: "Sunday", label: "Sun afternoon", startTime: "14:00", endTime: "16:00" },
];

export const defaultProfile: ResidentProfile = {
  id: "resident-demo",
  displayName: "Alex",
  email: "alex@example.com",
  phone: "+31 6 1234 5678",
  profileImage: brandAssets.profileCardImage,
  neighborhood: "Kralingen",
  travelRadiusKm: 4,
  interests: [],
  comfort: {
    smallGroups: true,
    oneToOne: false,
    publicPlacesOnly: true,
    communityHosted: true,
  },
  availability: [],
  routines: [],
};

export const sessions: ActivitySession[] = [
  {
    id: "walk-kralingse-plas",
    title: "Evening walk around Kralingse Plas",
    interest: "walking",
    locationName: "Kralingse Plas entrance",
    neighborhood: "Kralingen",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Rotterdam Library Walks",
    groupSize: "small_group",
    capacity: 5,
    confirmedCount: 3,
    time: availabilityOptions[1],
    status: "open",
  },
  {
    id: "museum-coffee",
    title: "Depot Boijmans visit + cafe",
    interest: "museums",
    locationName: "Depot Boijmans Van Beuningen",
    neighborhood: "Museumpark",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Museumpark vrijwilligers",
    groupSize: "small_group",
    capacity: 4,
    confirmedCount: 2,
    time: availabilityOptions[3],
    status: "open",
  },
  {
    id: "coffee-study",
    title: "Quiet coffee and study table",
    interest: "coffee",
    locationName: "Centrale Bibliotheek",
    neighborhood: "Centrum",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Bibliotheek Rotterdam",
    groupSize: "small_group",
    capacity: 6,
    confirmedCount: 4,
    time: availabilityOptions[0],
    status: "open",
  },
  {
    id: "padel-intro",
    title: "Beginner padel — no experience needed",
    interest: "padel",
    locationName: "Sportcentrum West",
    neighborhood: "Delfshaven",
    isPublicPlace: true,
    isCommunityHosted: false,
    groupSize: "small_group",
    capacity: 4,
    confirmedCount: 2,
    time: availabilityOptions[1],
    status: "open",
  },
  {
    id: "board-games-katendrecht",
    title: "Board games at Kaapse Brouwers",
    interest: "board_games",
    locationName: "Kaapse Brouwers",
    neighborhood: "Katendrecht",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Wijkraad Katendrecht",
    groupSize: "small_group",
    capacity: 5,
    confirmedCount: 3,
    time: availabilityOptions[2],
    status: "open",
  },
  {
    id: "cooking-charlois",
    title: "Saturday cooking swap",
    interest: "cooking",
    locationName: "Buurthuis Charlois",
    neighborhood: "Charlois",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Stichting Buurtwerk",
    groupSize: "small_group",
    capacity: 6,
    confirmedCount: 4,
    time: availabilityOptions[2],
    status: "open",
  },
  {
    id: "hackathon-ai-civic-tech",
    title: "Civic AI hackathon evening",
    interest: "hackathons",
    locationName: "Cambridge Innovation Center Rotterdam",
    neighborhood: "Centrum",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Rotterdam Tech Social",
    groupSize: "small_group",
    capacity: 12,
    confirmedCount: 8,
    time: { day: "Thursday", label: "Thu evening", startTime: "18:00", endTime: "21:30" },
    status: "open",
  },
  {
    id: "basketball-lloydkwartier",
    title: "Casual basketball at Lloyd Multiplein",
    interest: "basketball",
    locationName: "Lloyd Multiplein outdoor court",
    neighborhood: "Delfshaven",
    isPublicPlace: true,
    isCommunityHosted: false,
    hostName: "Open court crew",
    groupSize: "small_group",
    capacity: 10,
    confirmedCount: 7,
    time: { day: "Saturday", label: "Sat afternoon", startTime: "15:00", endTime: "17:00" },
    status: "open",
  },
  {
    id: "fencing-beginner-noord",
    title: "Beginner fencing lesson",
    interest: "fencing",
    locationName: "Schermzaal Rotterdam Noord",
    neighborhood: "Noord",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Rotterdam Fencing Club",
    groupSize: "small_group",
    capacity: 8,
    confirmedCount: 5,
    time: { day: "Wednesday", label: "Wed evening", startTime: "19:00", endTime: "20:30" },
    status: "open",
  },
  {
    id: "football-vroesenpark",
    title: "Beginner five-a-side football",
    interest: "football",
    locationName: "Vroesenpark sports field",
    neighborhood: "Noord",
    isPublicPlace: true,
    isCommunityHosted: false,
    hostName: "Sunday football group",
    groupSize: "small_group",
    capacity: 10,
    confirmedCount: 6,
    time: { day: "Sunday", label: "Sun morning", startTime: "10:30", endTime: "12:00" },
    status: "open",
  },
  {
    id: "startup-coffee-blak",
    title: "Indie builders coffee table",
    interest: "hackathons",
    locationName: "Blaak community cafe",
    neighborhood: "Centrum",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Founders Friday",
    groupSize: "small_group",
    capacity: 6,
    confirmedCount: 3,
    time: { day: "Friday", label: "Fri morning", startTime: "09:00", endTime: "10:30" },
    status: "open",
  },
  {
    id: "photo-walk-katendrecht",
    title: "Phone photography walk",
    interest: "photography",
    locationName: "Fenixloods entrance",
    neighborhood: "Katendrecht",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Fenix community hosts",
    groupSize: "small_group",
    capacity: 7,
    confirmedCount: 4,
    time: { day: "Saturday", label: "Sat afternoon", startTime: "14:00", endTime: "16:00" },
    status: "open",
  },
  {
    id: "language-table-library",
    title: "Dutch-English language table",
    interest: "languages",
    locationName: "Centrale Bibliotheek Rotterdam",
    neighborhood: "Centrum",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Bibliotheek Rotterdam",
    groupSize: "small_group",
    capacity: 8,
    confirmedCount: 5,
    time: { day: "Tuesday", label: "Tue evening", startTime: "18:30", endTime: "20:00" },
    status: "open",
  },
  {
    id: "music-open-mic-delfshaven",
    title: "Low-pressure open mic circle",
    interest: "music",
    locationName: "Delfshaven community stage",
    neighborhood: "Delfshaven",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Harbor Music Hosts",
    groupSize: "small_group",
    capacity: 9,
    confirmedCount: 6,
    time: { day: "Friday", label: "Fri evening", startTime: "19:30", endTime: "21:00" },
    status: "open",
  },
  {
    id: "swim-oostelijk",
    title: "Easy lane swim meetup",
    interest: "swimming",
    locationName: "Oostelijk Zwembad",
    neighborhood: "Kralingen",
    isPublicPlace: true,
    isCommunityHosted: false,
    hostName: "Morning swim group",
    groupSize: "small_group",
    capacity: 6,
    confirmedCount: 2,
    time: { day: "Wednesday", label: "Wed morning", startTime: "07:30", endTime: "08:30" },
    status: "open",
  },
  {
    id: "crafts-mending-museumpark",
    title: "Repair and mending table",
    interest: "crafts",
    locationName: "Het Nieuwe Instituut cafe",
    neighborhood: "Museumpark",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Makers Rotterdam",
    groupSize: "small_group",
    capacity: 6,
    confirmedCount: 3,
    time: { day: "Sunday", label: "Sun afternoon", startTime: "13:00", endTime: "15:00" },
    status: "open",
  },
];

export const neighborhoods = ["Kralingen", "Centrum", "Delfshaven", "Noord", "Museumpark", "Katendrecht", "Charlois", "Feijenoord", "Hillegersberg"];

export const routines = ["Evening walk", "Coffee break", "Museum visit", "Study block", "Weekend market", "Open court sports", "Hackathon night", "Beginner lesson"];
