import type { ActivitySession, AvailabilitySlot, ComfortKey, Interest, ResidentProfile } from "./types";

export const brandAssets = {
  logoWordmark: "Gesellig",
  logoMark: "https://www.figma.com/api/mcp/asset/56fe4e24-fc67-49db-bfc9-81042f09c4d7",
  heroImage: "https://www.figma.com/api/mcp/asset/6a35cccc-51a2-4ddb-b303-8a754ceaf661",
  cityCardImage: "https://www.figma.com/api/mcp/asset/62bb4bb6-a083-43a3-8305-ae2948979bee",
  profileCardImage: "https://www.figma.com/api/mcp/asset/aaeeafc5-e073-4507-927a-7aaa80cebaa5",
};

export const activityImages: Record<Interest, string> = {
  walking: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=300&h=300&fit=crop&q=80",
  museums: "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?w=300&h=300&fit=crop&q=80",
  coffee: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=300&h=300&fit=crop&q=80",
  studying: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=300&h=300&fit=crop&q=80",
  padel: "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=300&h=300&fit=crop&q=80",
  football: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=300&h=300&fit=crop&q=80",
  board_games: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=300&h=300&fit=crop&q=80",
  cooking: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=300&h=300&fit=crop&q=80",
  cinema: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=300&h=300&fit=crop&q=80",
  community_events: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=300&h=300&fit=crop&q=80",
  yoga: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=300&h=300&fit=crop&q=80",
  cycling: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=300&h=300&fit=crop&q=80",
  photography: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=300&h=300&fit=crop&q=80",
  music: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=300&h=300&fit=crop&q=80",
  gardening: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop&q=80",
  crafts: "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=300&h=300&fit=crop&q=80",
  swimming: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=300&h=300&fit=crop&q=80",
  dancing: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&h=300&fit=crop&q=80",
  languages: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=300&h=300&fit=crop&q=80",
  other: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=300&h=300&fit=crop&q=80",
};

export const peopleCards = [
  {
    name: "Ann James",
    image: "https://www.figma.com/api/mcp/asset/6a35cccc-51a2-4ddb-b303-8a754ceaf661",
    note: "Walking nearby",
    daysLeft: "7 days left",
  },
  {
    name: "Lauren Brand",
    image: "https://www.figma.com/api/mcp/asset/62bb4bb6-a083-43a3-8305-ae2948979bee",
    note: "Museum coffee",
    daysLeft: "7 days left",
  },
  {
    name: "Alex Thomas",
    image: "https://www.figma.com/api/mcp/asset/aaeeafc5-e073-4507-927a-7aaa80cebaa5",
    note: "Board games",
    daysLeft: "4 days left",
  },
];

export const interests: { id: Interest; label: string }[] = [
  { id: "coffee", label: "Coffee" },
  { id: "cinema", label: "Cinema" },
  { id: "football", label: "Football" },
  { id: "padel", label: "Padel" },
  { id: "walking", label: "Walking" },
  { id: "museums", label: "Museums" },
  { id: "board_games", label: "Board games" },
  { id: "studying", label: "Study session" },
  { id: "cooking", label: "Cooking" },
  { id: "community_events", label: "Local events" },
  { id: "yoga", label: "Yoga" },
  { id: "cycling", label: "Cycling" },
  { id: "photography", label: "Photography" },
  { id: "music", label: "Music" },
  { id: "gardening", label: "Gardening" },
  { id: "crafts", label: "Crafts" },
  { id: "swimming", label: "Swimming" },
  { id: "dancing", label: "Dancing" },
  { id: "languages", label: "Languages" },
  { id: "other", label: "Other" },
];

export const comfortOptions: { id: ComfortKey; label: string; helper: string }[] = [
  { id: "smallGroups", label: "Small groups", helper: "2-5 people" },
  { id: "oneToOne", label: "1:1 optional", helper: "Only if you choose it" },
  { id: "publicPlacesOnly", label: "Public places", helper: "Visible venues first" },
  { id: "communityHosted", label: "Hosted events", helper: "Partner or venue present" },
];

export const availabilityOptions: AvailabilitySlot[] = [
  { day: "Wednesday", label: "Wed afternoon", startTime: "15:00", endTime: "17:00" },
  { day: "Thursday", label: "Thu evening", startTime: "18:30", endTime: "20:00" },
  { day: "Saturday", label: "Sat morning", startTime: "10:00", endTime: "12:00" },
  { day: "Sunday", label: "Sun afternoon", startTime: "14:00", endTime: "16:00" },
];

export const defaultProfile: ResidentProfile = {
  id: "resident-demo",
  displayName: "Alex",
  email: "alex@example.com",
  phone: "+31 6 1234 5678",
  profileImage: brandAssets.profileCardImage,
  neighborhood: "Kralingen",
  travelRadiusKm: 4,
  interests: [],
  comfort: {
    smallGroups: true,
    oneToOne: false,
    publicPlacesOnly: true,
    communityHosted: true,
  },
  availability: [],
  routines: [],
};

export const sessions: ActivitySession[] = [
  {
    id: "walk-kralingse-plas",
    title: "Evening walk around Kralingse Plas",
    interest: "walking",
    locationName: "Kralingse Plas entrance",
    neighborhood: "Kralingen",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Rotterdam Library Walks",
    groupSize: "small_group",
    capacity: 5,
    confirmedCount: 3,
    time: availabilityOptions[1],
    status: "open",
  },
  {
    id: "museum-coffee",
    title: "Depot Boijmans visit + cafe",
    interest: "museums",
    locationName: "Depot Boijmans Van Beuningen",
    neighborhood: "Museumpark",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Museumpark vrijwilligers",
    groupSize: "small_group",
    capacity: 4,
    confirmedCount: 2,
    time: availabilityOptions[3],
    status: "open",
  },
  {
    id: "coffee-study",
    title: "Quiet coffee and study table",
    interest: "coffee",
    locationName: "Centrale Bibliotheek",
    neighborhood: "Centrum",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Bibliotheek Rotterdam",
    groupSize: "small_group",
    capacity: 6,
    confirmedCount: 4,
    time: availabilityOptions[0],
    status: "open",
  },
  {
    id: "padel-intro",
    title: "Beginner padel — no experience needed",
    interest: "padel",
    locationName: "Sportcentrum West",
    neighborhood: "Delfshaven",
    isPublicPlace: true,
    isCommunityHosted: false,
    groupSize: "small_group",
    capacity: 4,
    confirmedCount: 2,
    time: availabilityOptions[1],
    status: "open",
  },
  {
    id: "board-games-katendrecht",
    title: "Board games at Kaapse Brouwers",
    interest: "board_games",
    locationName: "Kaapse Brouwers",
    neighborhood: "Katendrecht",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Wijkraad Katendrecht",
    groupSize: "small_group",
    capacity: 5,
    confirmedCount: 3,
    time: availabilityOptions[2],
    status: "open",
  },
  {
    id: "cooking-charlois",
    title: "Saturday cooking swap",
    interest: "cooking",
    locationName: "Buurthuis Charlois",
    neighborhood: "Charlois",
    isPublicPlace: true,
    isCommunityHosted: true,
    hostName: "Stichting Buurtwerk",
    groupSize: "small_group",
    capacity: 6,
    confirmedCount: 4,
    time: availabilityOptions[2],
    status: "open",
  },
];

export const neighborhoods = ["Kralingen", "Centrum", "Delfshaven", "Noord", "Museumpark", "Katendrecht", "Charlois", "Feijenoord", "Hillegersberg"];

export const routines = ["Evening walk", "Coffee break", "Museum visit", "Study block", "Weekend market"];
